server:
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/shuttlayho
    driver-class-name: org.mariadb.jdbc.Driver
    username: ceri
    password: Tjflxla@@
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update